In [20]:
import numpy as np
import time as t
a = np.arange(21)
a%2==0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True])

In [21]:
# fancy indexing

a[a%2==0]
#or
mask = a%2==0
a[mask]
# %timeit a[mask]
a[(a%2==0) | (a%5==0)]
a[(a%2==0) & (a%5==0)]

array([ 0, 10, 20])

In [23]:
a[a%3==1] = -1
a

array([ 0, -1,  2,  3, -1,  5,  6, -1,  8,  9, -1, 11, 12, -1, 14, 15, -1,
       17, 18, -1, 20])

In [27]:
mat1 = np.arange(10)
mat2 = np.arange(10,20)
mat1
mat2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [25]:
# Addition
mat1 + mat2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [28]:
# subtraction
mat1 - mat2

array([-10, -10, -10, -10, -10, -10, -10, -10, -10, -10])

In [29]:
# Element - wise multiplication
mat1 * mat2

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [30]:
# division
mat1 / mat2

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421])

In [33]:
!gdown 14bd17pg9d3CbhcxdT6EGMDgvgMHrSjKR8

Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.
	Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?id=14bd17pg9d3CbhcxdT6EGMDgvgMHrSjKR8

but Gdown can't. Please check connections and permissions.
