In [21]:
import numpy as n
arr = n.arange(10).reshape(2,5)
arr

TypeError: 'int' object is not callable

In [10]:
array1 = n.array([
    1,2,3,4,5
])
# type(array1)#THis is a numpy.ndarray



In [13]:
print(array1)#numpy doesnot prints commas between the elements
n.array([1,2,3,4,4,5,True])

[1 2 3 4 5]


array([1, 2, 3, 4, 4, 5, 1])

In [24]:
d2 = n.array([[1,2,3],
              [6,7,8],
              [6,7,8]
            ])
d2.ndim
d2.shape#(rows,columns) --> always return in the form of tuple

(3, 3)

In [25]:
d = n.array([[1,2],
              [6,7],
              [6,7]
            ])
d.ndim
d.shape#(rows,columns)

(3, 2)

In [28]:
# numpy.arange(start,end,step_range) --> gives an array from [star,end) and will skip the numbers of step_size
# step size can be floating point numbers too, this is the main advantage of this arange function
x = n.arange(0,50,2.1)
x

array([ 0. ,  2.1,  4.2,  6.3,  8.4, 10.5, 12.6, 14.7, 16.8, 18.9, 21. ,
       23.1, 25.2, 27.3, 29.4, 31.5, 33.6, 35.7, 37.8, 39.9, 42. , 44.1,
       46.2, 48.3])

In [29]:
num = n.arange(0,10)
num[[1,2,3,6,1]]

array([1, 2, 3, 6, 1])