In [3]:
import numpy as np
import time as t
a = np.empty((3,3))
a.shape


(3, 3)

In [7]:
b = np.array([1,2,1,3,1,32,23,4,34,2,4,3,2,34,2,1,4,2,1])
np.unique(b,return_counts=True)
np.unique(b,return_index=True)
np.unique(b,return_inverse=True)


(array([ 1,  2,  3,  4, 23, 32, 34]),
 array([0, 1, 0, 2, 0, 5, 4, 3, 6, 1, 3, 2, 1, 6, 1, 0, 3, 1, 0],
       dtype=int64))

2D NDARRAYS 

In [24]:
x = np.array([[1,2,3,4],[5,6,7,8]])
x.shape
y = np.arange(15).reshape((3,5))
y.size#15
y.shape#(3,5)
len(y)#3
y.T#Transpose
y.shape

(5, 3)

In [28]:
y[2,1]
y

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [31]:
#Extracting one element
y[-1,-3]
# Extract multiple values : ndarray[ [ list of row indices ] , [ list of column indices ] ]
y[[0,2,3],[2,1,2]]


array([10,  7, 13])

SLICING 

In [32]:
array = np.arange(15).reshape((3,5))
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [36]:
array[:2:,:4:]
array[:3:,:4:]# array[:3,:4] -->similar as we can exclude the zeroes
array[:3:2,:4:2]

array([[ 0,  2],
       [10, 12]])