In [1]:
import numpy as np
import time as t
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

MASKING OPERATIONS

In [2]:
a<6

array([[ True,  True,  True,  True,  True],
       [ True, False, False, False, False],
       [False, False, False, False, False]])

In [6]:
a[a<9]
a[(a>10) & (a<14)]

array([11, 12, 13])

UNIVERSAL FUNCTIONS FOR 2D ARRAYS

In [15]:
a.sum()
np.average(a)
a.max()
a.min()
a.cumsum() 
a[0,0] = 1
a.cumprod()

array([         1,          1,          2,          6,         24,
              120,        720,       5040,      40320,     362880,
          3628800,   39916800,  479001600, 1932053504, 1278945280])

AXIS 

In [24]:
a.sum(axis=1)#axis = 1 means rows i.e. horizontal axis
a.sum(axis=0)#axis = 0 means columns i.e. vertical axis
a.mean(axis=1)
a
round(a.mean(),2)
a.sum(axis=-1)# means same as axis = 1 because the tuple for 2D arrays is (0,1)

array([11, 35, 60])

LOGICAL OPERATIONS

In [30]:
x = np.arange(1,16).reshape(3,5)
y = np.arange(16,31).reshape(3,5)
x<y
np.any(x<y)#It works like logical OR where if any one element is satifying the condition then it will return true
np.all(x>2)#It works like logical AND when all the elements are satifying the condition then it will return true

False